development:
  adapter: postgresql
  host: web443.webfaction.com
  port: 5432
  encoding: utf8
  database: drunkskunkdb
  pool: 5
  username: lhkastenson
  password: Xtpg1946!

test: &TEST
  adapter: postgresql
  host: web443.webfaction.com
  port: 5432
  encoding: utf8
  database: drunkskunkdb
  pool: 5
  username: lhkastenson
  password: Xtpg1946!

production:
  adapter: postgresql
  host: web443.webfaction.com
  port: 5432
  encoding: utf8
  database: drunkskunkdb
  pool: 5
  username: lhkastenson
  password: Xtpg1946!